### ISSUE TITLE
Broken "experiments launch" command

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#7]
Launching experiments with variants yields the error:
```
AttributeError: 'dict' object has no attribute 'append'
```
which is triggered here:
https://github.com/hu-macsy/simexpal/blob/0f656e73e88a3a0cbcef0c6cc28ba9889f7b5cbf/simexpal/launch/common.py#L173
probably because `variants_yml` is a `dict`. 

Also, if I drop the variants I get the error:
```
AttributeError: 'RunManifest' object has no attribute 'time'
```
triggered here:
https://github.com/hu-macsy/simexpal/blob/0f656e73e88a3a0cbcef0c6cc28ba9889f7b5cbf/simexpal/launch/common.py#L280

Are those bugs or am I doing something wrong?

**Comment by avdgrinten** [comment]
Can you post the `experiments.yml` file (at least the relevant parts)?

**Comment by avdgrinten** [comment]
https://github.com/hu-macsy/simexpal/blob/0f656e73e88a3a0cbcef0c6cc28ba9889f7b5cbf/simexpal/launch/common.py#L280
Here, the `manifest.time` should be `manifest.timeout`.

**Comment by angriman** [comment]
I will upload an `experiments.txt` as `.yml` files are not supported by GitHub.

**Comment by avdgrinten** [comment]
https://github.com/hu-macsy/simexpal/blob/0f656e73e88a3a0cbcef0c6cc28ba9889f7b5cbf/simexpal/launch/common.py#L171
This should be a list.

**Comment by angriman** [comment]
Attached my experiments yaml file:
[experiments.txt](https://github.com/hu-macsy/simexpal/files/3350883/experiments.txt)

**Comment by angriman** [comment]
I corrected those two lines as suggested, now it seems to work correctly.

**Comment by avdgrinten** [comment]
Great. You can merge the changes. This was caused by a rewrite of the launch infrastructure. simexpal now collects the commands that will be launched in a file (the "manifest"). The process launched by the queue scheduler looks at this file to determine what command to run. This makes sure that the queue scheduler runs exactly the jobs that we want to run; e.g., it even works if the `experiments.yml` is modified in the between job submission and job execution.
